// Alle teksten van de app op één plek.
// Eigennamen en bijnamen (The Great Random Race, The Unreasonably Slow)
// blijven bewust Engels.

export const nl = {
  app: {
    name: 'The Great Random Race',
    logoAlt: 'The Great Random Race',
  },
  nav: {
    label: 'Hoofdmenu',
    home: 'Home',
    race: 'Race',
    collection: 'Collectie',
    soon: 'binnenkort',
    more: 'Meer',
  },
  common: {
    back: 'Terug',
    of: 'van',
    racers: 'racers',
    daysLeft: (n: number) => (n === 1 ? 'Nog 1 dag' : `Nog ${n} dagen`),
    raceNumber: (n: number) => `Race #${n}`,
    sampleNotice: 'Testversie: de getallen en berichten zijn nog voorbeelden.',
  },
  welcome: {
    title: 'Dit is Gerard.',
    intro: 'Hij is een slak. Hij doet mee aan een race van zeven dagen. Niemand weet precies waarom.',
    relax: 'Jij hoeft niets te doen. Kom gewoon af en toe kijken wat hij uitspookt.',
    installTitle: 'Zet Gerard op je beginscherm.',
    installIphone: 'iPhone: tik op',
    installIphoneShare: 'Delen',
    installIphoneChoose: 'en kies',
    installIphoneAction: 'Zet op beginscherm',
    installAndroid: 'Android: tik op',
    installAndroidMenu: '⋮',
    installAndroidAction: 'App installeren',
    installWhy: 'Dan raakt hij zijn race nooit kwijt.',
    start: 'Start de race',
    gerardAlt: 'Gerard de slak',
  },
  home: {
    settings: 'Meer opties',
    currently: (name: string) => `${name} is momenteel…`,
    viewRace: 'Bekijk race',
    yourPosition: 'Jouw positie',
    now: (pos: number) => `nu #${pos}`,
    actionTitle: 'Actie van vandaag',
    actionOpen: 'Je mag vandaag nog iets doen voor Gerard.',
  },
  race: {
    openJournal: 'Journaal openen',
    finish: 'Finish',
    mapAlt: (name: string, pos: number) =>
      `Geïllustreerde kaart van De Grote Bosrace met ${name} op plek ${pos}`,
  },
  racer: {
    races: 'Races',
    wins: 'Overwinningen',
    bestPosition: 'Beste positie',
    traitsTitle: 'Eigenschappen',
    speed: 'Snelheid',
    curious: 'Nieuwsgierigheid',
    stubborn: 'Koppigheid',
    chaotic: 'Chaos',
    lazy: 'Luiheid',
    favoriteFood: 'Favoriete eten',
    dislikes: 'Kan niet tegen',
    favoriteActivity: 'Favoriete activiteit',
    secretTalent: 'Geheime talent',
    inLandscape: (name: string) => `${name} in het landschap`,
  },
  leaderboard: {
    title: 'Tussenstand',
    place: (n: number) => `${n}e plaats`,
  },
  journal: {
    title: (name: string) => `${name}s journaal`,
  },
  action: {
    title: 'Actie van vandaag',
    intro: 'Je mag één ding doen voor Gerard. Kies verstandig. Of niet.',
    confirm: 'Doe het',
    done: 'Gedaan.',
    tomorrow: 'Morgen weer een actie',
    footer: 'Eén actie per dag. Het effect is klein. Gerard waardeert het toch.',
    options: {
      voeren: {
        title: 'Gerard voeren',
        effect: 'Een blaadje sla. 12 uur iets sneller.',
        after: 'Gerard heeft zijn sla. Hij kijkt er al een tijdje naar.',
      },
      aanmoedigen: {
        title: 'Gerard aanmoedigen',
        effect: 'Een hele dag een klein beetje sneller.',
        after: 'Gerard is aangemoedigd. Hij lijkt het gehoord te hebben.',
      },
      hoed: {
        title: 'Gerard een hoed geven',
        effect: 'Geen effect op snelheid. Wel op stijl.',
        after: 'Gerard draagt nu een hoed. De andere racers hebben het gezien.',
      },
      niets: {
        title: 'Niets doen',
        effect: 'Gerard waardeert de rust.',
        after: 'Je hebt niets gedaan. Gerard vond dat prima.',
      },
    },
  },
  event: {
    badge: 'Event!',
    close: 'Sluiten',
  },
  finish: {
    badge: 'Finish!',
    winner: (name: string) => `${name} heeft gewonnen!`,
    place: (name: string, pos: number) => `${name} werd ${pos}e!`,
    winnerAlt: (name: string) => `${name} met kroontje, de winnaar`,
    podium: 'Podium',
    statsTitle: 'Statistieken die niemand vroeg',
    newRace: 'Nieuwe race',
  },
  more: {
    title: 'Meer',
    raceSection: 'De race',
    leaderboard: 'Tussenstand',
    leaderboardHint: 'Wie ligt waar?',
    journal: 'Journaal',
    journalHint: 'Alles wat Gerard heeft meegemaakt.',
    action: 'Actie van vandaag',
    actionHint: 'Eén keer per dag iets doen voor Gerard.',
    previewSection: 'Testversie: bekijk de andere schermen',
    welcome: 'Eerste start',
    welcomeHint: 'Het welkomstscherm.',
    event: 'Keuze-event',
    eventHint: 'De pop-up met de gigantische aardbei.',
    finish: 'Finish',
    finishHint: 'De uitslag, met confetti.',
    privacy: 'Deze app verzamelt niets. Geen cookies, geen tracking. Alles blijft op je telefoon.',
  },
  notFound: {
    title: 'Hier is niets.',
    text: 'Gerard is hier ook nooit geweest.',
    home: 'Naar huis',
  },
};
